version: '2'
services:
  app:
    build: .
    links:
      - db:mongodb

  haproxy:
    build:
      context: .
      dockerfile: haproxy.Dockerfile
    ports:
      - 8080:80
    links:
      - app:app

  db:
    image: mongo:4.2
    command: mongod --logpath=/dev/null
